name: end_padding
description: A package that provides utils for creating ending padding in lists.
version: 1.0.1
repository: https://github.com/2-5-perceivers/end-padding
funding:
  - https://github.com/sponsors/rares45
  - https://buymeacoffee.com/raresvanca
topics: 
  - lists
  - widgets
  - padding
screenshots:
  - description: Colored EndPadding
    path: images/padding.jpg

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
